name: Deploy siop master to ci

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@master    

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/siop:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/siop:$GITHUB_SHA

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Rollout latest image to CI
      run:  |
        kubectl -n siop rollout restart deployment/siop
